#pragma checksum "C:\Users\liuzh\Source\Repos\ExViewer\ExClient\Strings\en\Category.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "CBDEED96F83F27C235105F8841A684C9"
#pragma checksum "C:\Users\liuzh\Source\Repos\ExViewer\ExClient\Strings\en\Language.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "912E30BD324694869546D145E37543FD"
#pragma checksum "C:\Users\liuzh\Source\Repos\ExViewer\ExClient\Strings\en\Namespace.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "9FD2C912A98D71E10D7C385BBBC10DD1"
#pragma checksum "C:\Users\liuzh\Source\Repos\ExViewer\ExClient\Strings\en\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "06428982314F65EA11E915A237EDF164"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExClient.ExClient_ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
    internal interface ICategory : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>All</para>
        /// </summary>
        string All { get; }
        /// <summary>
        /// <para>Artist CG</para>
        /// </summary>
        string ArtistCG { get; }
        /// <summary>
        /// <para>Asian Porn</para>
        /// </summary>
        string AsianPorn { get; }
        /// <summary>
        /// <para>Cosplay</para>
        /// </summary>
        string Cosplay { get; }
        /// <summary>
        /// <para>Doujinshi</para>
        /// </summary>
        string Doujinshi { get; }
        /// <summary>
        /// <para>Game CG</para>
        /// </summary>
        string GameCG { get; }
        /// <summary>
        /// <para>Image Set</para>
        /// </summary>
        string ImageSet { get; }
        /// <summary>
        /// <para>Manga</para>
        /// </summary>
        string Manga { get; }
        /// <summary>
        /// <para>Misc</para>
        /// </summary>
        string Misc { get; }
        /// <summary>
        /// <para>Non-H</para>
        /// </summary>
        string NonH { get; }
        /// <summary>
        /// <para>Unspecified</para>
        /// </summary>
        string Unspecified { get; }
        /// <summary>
        /// <para>Western</para>
        /// </summary>
        string Western { get; }
    }
}

namespace ExClient.ExClient_ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
    internal interface ILanguage : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::ExClient.ExClient_ResourceInfo.Language.IModifiers Modifiers { get; }
        global::ExClient.ExClient_ResourceInfo.Language.INames Names { get; }
    }
}

namespace ExClient.ExClient_ResourceInfo.Language
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
    internal interface IModifiers : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>TR</para>
        /// </summary>
        string Translated { get; }
        /// <summary>
        /// <para>RW</para>
        /// </summary>
        string Rewrite { get; }
    }
}

namespace ExClient.ExClient_ResourceInfo.Language
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
    internal interface INames : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Albanian</para>
        /// </summary>
        string Albanian { get; }
        /// <summary>
        /// <para>Arabic</para>
        /// </summary>
        string Arabic { get; }
        /// <summary>
        /// <para>Bengali</para>
        /// </summary>
        string Bengali { get; }
        /// <summary>
        /// <para>Catalan</para>
        /// </summary>
        string Catalan { get; }
        /// <summary>
        /// <para>Chinese</para>
        /// </summary>
        string Chinese { get; }
        /// <summary>
        /// <para>Czech</para>
        /// </summary>
        string Czech { get; }
        /// <summary>
        /// <para>Danish</para>
        /// </summary>
        string Danish { get; }
        /// <summary>
        /// <para>Dutch</para>
        /// </summary>
        string Dutch { get; }
        /// <summary>
        /// <para>English</para>
        /// </summary>
        string English { get; }
        /// <summary>
        /// <para>Esperanto</para>
        /// </summary>
        string Esperanto { get; }
        /// <summary>
        /// <para>Estonian</para>
        /// </summary>
        string Estonian { get; }
        /// <summary>
        /// <para>Finnish</para>
        /// </summary>
        string Finnish { get; }
        /// <summary>
        /// <para>French</para>
        /// </summary>
        string French { get; }
        /// <summary>
        /// <para>German</para>
        /// </summary>
        string German { get; }
        /// <summary>
        /// <para>Greek</para>
        /// </summary>
        string Greek { get; }
        /// <summary>
        /// <para>Hebrew</para>
        /// </summary>
        string Hebrew { get; }
        /// <summary>
        /// <para>Hindi</para>
        /// </summary>
        string Hindi { get; }
        /// <summary>
        /// <para>Hungarian</para>
        /// </summary>
        string Hungarian { get; }
        /// <summary>
        /// <para>Indonesian</para>
        /// </summary>
        string Indonesian { get; }
        /// <summary>
        /// <para>Italian</para>
        /// </summary>
        string Italian { get; }
        /// <summary>
        /// <para>Japanese</para>
        /// </summary>
        string Japanese { get; }
        /// <summary>
        /// <para>Korean</para>
        /// </summary>
        string Korean { get; }
        /// <summary>
        /// <para>Mongolian</para>
        /// </summary>
        string Mongolian { get; }
        /// <summary>
        /// <para>Norwegian</para>
        /// </summary>
        string Norwegian { get; }
        /// <summary>
        /// <para>N/A</para>
        /// </summary>
        string NotApplicable { get; }
        /// <summary>
        /// <para>Other</para>
        /// </summary>
        string Other { get; }
        /// <summary>
        /// <para>Polish</para>
        /// </summary>
        string Polish { get; }
        /// <summary>
        /// <para>Portuguese</para>
        /// </summary>
        string Portuguese { get; }
        /// <summary>
        /// <para>Romanian</para>
        /// </summary>
        string Romanian { get; }
        /// <summary>
        /// <para>Russian</para>
        /// </summary>
        string Russian { get; }
        /// <summary>
        /// <para>Slovak</para>
        /// </summary>
        string Slovak { get; }
        /// <summary>
        /// <para>Slovenian</para>
        /// </summary>
        string Slovenian { get; }
        /// <summary>
        /// <para>Spanish</para>
        /// </summary>
        string Spanish { get; }
        /// <summary>
        /// <para>Swedish</para>
        /// </summary>
        string Swedish { get; }
        /// <summary>
        /// <para>Tagalog</para>
        /// </summary>
        string Tagalog { get; }
        /// <summary>
        /// <para>Thai</para>
        /// </summary>
        string Thai { get; }
        /// <summary>
        /// <para>Turkish</para>
        /// </summary>
        string Turkish { get; }
        /// <summary>
        /// <para>Ukrainian</para>
        /// </summary>
        string Ukrainian { get; }
        /// <summary>
        /// <para>Vietnamese</para>
        /// </summary>
        string Vietnamese { get; }
    }
}

namespace ExClient.ExClient_ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
    internal interface INamespace : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Artist</para>
        /// </summary>
        string Artist { get; }
        /// <summary>
        /// <para>Character</para>
        /// </summary>
        string Character { get; }
        /// <summary>
        /// <para>Female</para>
        /// </summary>
        string Female { get; }
        /// <summary>
        /// <para>Group</para>
        /// </summary>
        string Group { get; }
        /// <summary>
        /// <para>Language</para>
        /// </summary>
        string Language { get; }
        /// <summary>
        /// <para>Male</para>
        /// </summary>
        string Male { get; }
        /// <summary>
        /// <para>Misc</para>
        /// </summary>
        string Misc { get; }
        /// <summary>
        /// <para>Parody</para>
        /// </summary>
        string Parody { get; }
        /// <summary>
        /// <para>Reclass</para>
        /// </summary>
        string Reclass { get; }
        /// <summary>
        /// <para>Unknown</para>
        /// </summary>
        string Unknown { get; }
    }
}

namespace ExClient.ExClient_ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>This account dose not have permittion for exhentai.</para>
        /// </summary>
        string NoExPermittion { get; }
        /// <summary>
        /// <para>All favorites</para>
        /// </summary>
        string AllFavorites { get; }
        /// <summary>
        /// <para>Remove from favorites</para>
        /// </summary>
        string RemoveFromFavorites { get; }
        /// <summary>
        /// <para>The client has been disposed.</para>
        /// </summary>
        string ClientDisposed { get; }
        /// <summary>
        /// <para>Gallery Title</para>
        /// </summary>
        string DefaultTitle { get; }
        /// <summary>
        /// <para>Uploader</para>
        /// </summary>
        string DefaultUploader { get; }
        /// <summary>
        /// <para>This torrent has beem expunged.</para>
        /// </summary>
        string ExpungedTorrent { get; }
        /// <summary>
        /// <para>Only IPV4 address supported.</para>
        /// </summary>
        string OnlyIpv4 { get; }
        /// <summary>
        /// <para>User name or password incorrect.</para>
        /// </summary>
        string WrongAccountInfo { get; }
        /// <summary>
        /// <para>The captcha was not entered correctly. Please try again.</para>
        /// </summary>
        string WrongCaptcha { get; }
        /// <summary>
        /// <para>The response of the server can&#39;t be analyzed.</para>
        /// </summary>
        string WrongVoteResponse { get; }
        /// <summary>
        /// <para>Can&#39;t vote when you had posted a comment.</para>
        /// </summary>
        string WrongVoteState { get; }
        /// <summary>
        /// <para>Can only edit own comment.</para>
        /// </summary>
        string WrongEditState { get; }
        /// <summary>
        /// <para>You did not enter a valid comment.</para>
        /// </summary>
        string EmptyComment { get; }
        /// <summary>
        /// <para>Your comment is too short.</para>
        /// </summary>
        string ShortComment { get; }
        /// <summary>
        /// <para>You can only add comments for active galleries.</para>
        /// </summary>
        string WrongGalleryState { get; }
    }
}

namespace ExClient
{
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
    internal static class LocalizedStrings
    {

        internal static global::ExClient.ExClient_ResourceInfo.ICategory Category { get; } = new global::ExClient.LocalizedStrings.Category__eOfP2ONa();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
        [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///ExClient/Category]")]
        private sealed class Category__eOfP2ONa : global::ExClient.ExClient_ResourceInfo.ICategory
        {
            global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
            {
                get
                {
                    if(resourceKey == null)
                        throw new global::System.ArgumentNullException();
                    return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///ExClient/Category/" + resourceKey);
                }
            }

            string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
            {
                return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/" + resourceKey);
            }


            string global::ExClient.ExClient_ResourceInfo.ICategory.All
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/All");
            string global::ExClient.ExClient_ResourceInfo.ICategory.ArtistCG
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/ArtistCG");
            string global::ExClient.ExClient_ResourceInfo.ICategory.AsianPorn
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/AsianPorn");
            string global::ExClient.ExClient_ResourceInfo.ICategory.Cosplay
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/Cosplay");
            string global::ExClient.ExClient_ResourceInfo.ICategory.Doujinshi
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/Doujinshi");
            string global::ExClient.ExClient_ResourceInfo.ICategory.GameCG
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/GameCG");
            string global::ExClient.ExClient_ResourceInfo.ICategory.ImageSet
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/ImageSet");
            string global::ExClient.ExClient_ResourceInfo.ICategory.Manga
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/Manga");
            string global::ExClient.ExClient_ResourceInfo.ICategory.Misc
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/Misc");
            string global::ExClient.ExClient_ResourceInfo.ICategory.NonH
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/NonH");
            string global::ExClient.ExClient_ResourceInfo.ICategory.Unspecified
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/Unspecified");
            string global::ExClient.ExClient_ResourceInfo.ICategory.Western
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Category/Western");
        }

        internal static global::ExClient.ExClient_ResourceInfo.ILanguage Language { get; } = new global::ExClient.LocalizedStrings.Language__2_BkPflE();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
        [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///ExClient/Language]")]
        private sealed class Language__2_BkPflE : global::ExClient.ExClient_ResourceInfo.ILanguage
        {
            global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
            {
                get
                {
                    if(resourceKey == null)
                        throw new global::System.ArgumentNullException();
                    return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///ExClient/Language/" + resourceKey);
                }
            }

            string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
            {
                return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/" + resourceKey);
            }


            global::ExClient.ExClient_ResourceInfo.Language.IModifiers global::ExClient.ExClient_ResourceInfo.ILanguage.Modifiers { get; } = new global::ExClient.LocalizedStrings.Language__2_BkPflE.Modifiers__u6q6fyzv();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///ExClient/Language/Modifiers]", Name = "Modifiers")]
            private sealed class Modifiers__u6q6fyzv : global::ExClient.ExClient_ResourceInfo.Language.IModifiers
            {
                global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///ExClient/Language/Modifiers/" + resourceKey);
                    }
                }

                string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Modifiers");
                    return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Modifiers/" + resourceKey);
                }

                string global::ExClient.ExClient_ResourceInfo.Language.IModifiers.Translated
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Modifiers/Translated");
                string global::ExClient.ExClient_ResourceInfo.Language.IModifiers.Rewrite
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Modifiers/Rewrite");
            }

            global::ExClient.ExClient_ResourceInfo.Language.INames global::ExClient.ExClient_ResourceInfo.ILanguage.Names { get; } = new global::ExClient.LocalizedStrings.Language__2_BkPflE.Names__x6StKouE();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///ExClient/Language/Names]", Name = "Names")]
            private sealed class Names__x6StKouE : global::ExClient.ExClient_ResourceInfo.Language.INames
            {
                global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///ExClient/Language/Names/" + resourceKey);
                    }
                }

                string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names");
                    return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/" + resourceKey);
                }

                string global::ExClient.ExClient_ResourceInfo.Language.INames.Albanian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Albanian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Arabic
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Arabic");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Bengali
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Bengali");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Catalan
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Catalan");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Chinese
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Chinese");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Czech
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Czech");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Danish
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Danish");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Dutch
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Dutch");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.English
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/English");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Esperanto
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Esperanto");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Estonian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Estonian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Finnish
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Finnish");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.French
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/French");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.German
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/German");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Greek
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Greek");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Hebrew
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Hebrew");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Hindi
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Hindi");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Hungarian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Hungarian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Indonesian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Indonesian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Italian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Italian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Japanese
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Japanese");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Korean
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Korean");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Mongolian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Mongolian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Norwegian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Norwegian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.NotApplicable
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/NotApplicable");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Other
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Other");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Polish
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Polish");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Portuguese
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Portuguese");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Romanian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Romanian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Russian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Russian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Slovak
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Slovak");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Slovenian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Slovenian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Spanish
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Spanish");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Swedish
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Swedish");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Tagalog
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Tagalog");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Thai
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Thai");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Turkish
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Turkish");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Ukrainian
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Ukrainian");
                string global::ExClient.ExClient_ResourceInfo.Language.INames.Vietnamese
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Language/Names/Vietnamese");
            }

        }

        internal static global::ExClient.ExClient_ResourceInfo.INamespace Namespace { get; } = new global::ExClient.LocalizedStrings.Namespace__HDDjW1sb();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
        [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///ExClient/Namespace]")]
        private sealed class Namespace__HDDjW1sb : global::ExClient.ExClient_ResourceInfo.INamespace
        {
            global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
            {
                get
                {
                    if(resourceKey == null)
                        throw new global::System.ArgumentNullException();
                    return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///ExClient/Namespace/" + resourceKey);
                }
            }

            string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
            {
                return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/" + resourceKey);
            }


            string global::ExClient.ExClient_ResourceInfo.INamespace.Artist
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Artist");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Character
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Character");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Female
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Female");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Group
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Group");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Language
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Language");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Male
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Male");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Misc
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Misc");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Parody
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Parody");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Reclass
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Reclass");
            string global::ExClient.ExClient_ResourceInfo.INamespace.Unknown
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Namespace/Unknown");
        }

        internal static global::ExClient.ExClient_ResourceInfo.IResources Resources { get; } = new global::ExClient.LocalizedStrings.Resources__CKm7lrVf();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.1.0")]
        [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///ExClient/Resources]")]
        private sealed class Resources__CKm7lrVf : global::ExClient.ExClient_ResourceInfo.IResources
        {
            global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
            {
                get
                {
                    if(resourceKey == null)
                        throw new global::System.ArgumentNullException();
                    return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///ExClient/Resources/" + resourceKey);
                }
            }

            string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
            {
                return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/" + resourceKey);
            }


            string global::ExClient.ExClient_ResourceInfo.IResources.NoExPermittion
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/NoExPermittion");
            string global::ExClient.ExClient_ResourceInfo.IResources.AllFavorites
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/AllFavorites");
            string global::ExClient.ExClient_ResourceInfo.IResources.RemoveFromFavorites
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/RemoveFromFavorites");
            string global::ExClient.ExClient_ResourceInfo.IResources.ClientDisposed
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/ClientDisposed");
            string global::ExClient.ExClient_ResourceInfo.IResources.DefaultTitle
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/DefaultTitle");
            string global::ExClient.ExClient_ResourceInfo.IResources.DefaultUploader
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/DefaultUploader");
            string global::ExClient.ExClient_ResourceInfo.IResources.ExpungedTorrent
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/ExpungedTorrent");
            string global::ExClient.ExClient_ResourceInfo.IResources.OnlyIpv4
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/OnlyIpv4");
            string global::ExClient.ExClient_ResourceInfo.IResources.WrongAccountInfo
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/WrongAccountInfo");
            string global::ExClient.ExClient_ResourceInfo.IResources.WrongCaptcha
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/WrongCaptcha");
            string global::ExClient.ExClient_ResourceInfo.IResources.WrongVoteResponse
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/WrongVoteResponse");
            string global::ExClient.ExClient_ResourceInfo.IResources.WrongVoteState
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/WrongVoteState");
            string global::ExClient.ExClient_ResourceInfo.IResources.WrongEditState
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/WrongEditState");
            string global::ExClient.ExClient_ResourceInfo.IResources.EmptyComment
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/EmptyComment");
            string global::ExClient.ExClient_ResourceInfo.IResources.ShortComment
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/ShortComment");
            string global::ExClient.ExClient_ResourceInfo.IResources.WrongGalleryState
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///ExClient/Resources/WrongGalleryState");
        }
    }
}
