#pragma checksum "C:\Users\lzy\Documents\Source\ExViewer\ExDawnOfDayTask\Strings\en\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "0F238DF07D52C197136A5CF0CF95D2D3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExDawnOfDayTask.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast DawnOfDayToast { get; }
    }
}

namespace ExDawnOfDayTask.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IDawnOfDayToast : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>You gain {reward1}!</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Content1();
        /// <summary>
        /// <para>You gain {reward1}!</para>
        /// </summary>
        string Content1(object reward1);
        /// <summary>
        /// <para>You gain {reward1}!</para>
        /// </summary>
        string Content1(global::System.IFormatProvider provider, object reward1);
        /// <summary>
        /// <para>You gain {reward1} and {reward2}!</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Content2();
        /// <summary>
        /// <para>You gain {reward1} and {reward2}!</para>
        /// </summary>
        string Content2(object reward1, object reward2);
        /// <summary>
        /// <para>You gain {reward1} and {reward2}!</para>
        /// </summary>
        string Content2(global::System.IFormatProvider provider, object reward1, object reward2);
        /// <summary>
        /// <para>You gain {reward1}, {reward2} and {reward3}!</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Content3();
        /// <summary>
        /// <para>You gain {reward1}, {reward2} and {reward3}!</para>
        /// </summary>
        string Content3(object reward1, object reward2, object reward3);
        /// <summary>
        /// <para>You gain {reward1}, {reward2} and {reward3}!</para>
        /// </summary>
        string Content3(global::System.IFormatProvider provider, object reward1, object reward2, object reward3);
        /// <summary>
        /// <para>You gain {reward1}, {reward2}, {reward3} and {reward4}!</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Content4();
        /// <summary>
        /// <para>You gain {reward1}, {reward2}, {reward3} and {reward4}!</para>
        /// </summary>
        string Content4(object reward1, object reward2, object reward3, object reward4);
        /// <summary>
        /// <para>You gain {reward1}, {reward2}, {reward3} and {reward4}!</para>
        /// </summary>
        string Content4(global::System.IFormatProvider provider, object reward1, object reward2, object reward3, object reward4);
        /// <summary>
        /// <para>{value} Credits</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString RewardCredits();
        /// <summary>
        /// <para>{value} Credits</para>
        /// </summary>
        string RewardCredits(object value);
        /// <summary>
        /// <para>{value} Credits</para>
        /// </summary>
        string RewardCredits(global::System.IFormatProvider provider, object value);
        /// <summary>
        /// <para>{value} EXP</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString RewardExp();
        /// <summary>
        /// <para>{value} EXP</para>
        /// </summary>
        string RewardExp(object value);
        /// <summary>
        /// <para>{value} EXP</para>
        /// </summary>
        string RewardExp(global::System.IFormatProvider provider, object value);
        /// <summary>
        /// <para>{value} GP</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString RewardGp();
        /// <summary>
        /// <para>{value} GP</para>
        /// </summary>
        string RewardGp(object value);
        /// <summary>
        /// <para>{value} GP</para>
        /// </summary>
        string RewardGp(global::System.IFormatProvider provider, object value);
        /// <summary>
        /// <para>{value} Hath</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString RewardHath();
        /// <summary>
        /// <para>{value} Hath</para>
        /// </summary>
        string RewardHath(object value);
        /// <summary>
        /// <para>{value} Hath</para>
        /// </summary>
        string RewardHath(global::System.IFormatProvider provider, object value);
        /// <summary>
        /// <para>It is the dawn of a new day!</para>
        /// </summary>
        string Title { get; }
    }
}

namespace ExDawnOfDayTask
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal static class Strings
    {

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::ExDawnOfDayTask.ResourceInfo.IResources Resources__AJUXmtL7;
        internal static global::ExDawnOfDayTask.ResourceInfo.IResources Resources 
            => global::System.Threading.LazyInitializer.EnsureInitialized(ref Resources__AJUXmtL7, () => new global::ExDawnOfDayTask.Strings.Resources__LLBa6oN1());

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
        private sealed class Resources__LLBa6oN1 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::ExDawnOfDayTask.ResourceInfo.IResources
        {
            public Resources__LLBa6oN1() : base("ms-resource:///ExDawnOfDayTask/Resources/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast DawnOfDayToast___zFM3asE;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast")]
            global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast global::ExDawnOfDayTask.ResourceInfo.IResources.DawnOfDayToast 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.DawnOfDayToast___zFM3asE, () => new global::ExDawnOfDayTask.Strings.Resources__LLBa6oN1.DawnOfDayToast__Tpxissxe());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class DawnOfDayToast__Tpxissxe : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast
            {
                public DawnOfDayToast__Tpxissxe() : base("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/") { }

                global::Opportunity.ResourceGenerator.FormattableResourceString Content1__2BtsWyNg;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content1")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content1()
                {
                    if (Content1__2BtsWyNg == null)
                        Content1__2BtsWyNg = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content1"));
                    return Content1__2BtsWyNg;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content1(object reward1)
                {
                    if (Content1__2BtsWyNg == null)
                        Content1__2BtsWyNg = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content1"));
                    return string.Format(Content1__2BtsWyNg.FormatString, reward1);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content1(global::System.IFormatProvider provider, object reward1)
                {
                    if (Content1__2BtsWyNg == null)
                        Content1__2BtsWyNg = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content1"));
                    return string.Format(provider, Content1__2BtsWyNg.FormatString, reward1);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString Content2__rY_5Frqa;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content2")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content2()
                {
                    if (Content2__rY_5Frqa == null)
                        Content2__rY_5Frqa = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content2"));
                    return Content2__rY_5Frqa;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content2(object reward1, object reward2)
                {
                    if (Content2__rY_5Frqa == null)
                        Content2__rY_5Frqa = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content2"));
                    return string.Format(Content2__rY_5Frqa.FormatString, reward1, reward2);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content2(global::System.IFormatProvider provider, object reward1, object reward2)
                {
                    if (Content2__rY_5Frqa == null)
                        Content2__rY_5Frqa = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content2"));
                    return string.Format(provider, Content2__rY_5Frqa.FormatString, reward1, reward2);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString Content3__9E0Rr26k;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content3")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content3()
                {
                    if (Content3__9E0Rr26k == null)
                        Content3__9E0Rr26k = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content3"));
                    return Content3__9E0Rr26k;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content3(object reward1, object reward2, object reward3)
                {
                    if (Content3__9E0Rr26k == null)
                        Content3__9E0Rr26k = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content3"));
                    return string.Format(Content3__9E0Rr26k.FormatString, reward1, reward2, reward3);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content3(global::System.IFormatProvider provider, object reward1, object reward2, object reward3)
                {
                    if (Content3__9E0Rr26k == null)
                        Content3__9E0Rr26k = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content3"));
                    return string.Format(provider, Content3__9E0Rr26k.FormatString, reward1, reward2, reward3);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString Content4__zHY0aLr9;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content4")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content4()
                {
                    if (Content4__zHY0aLr9 == null)
                        Content4__zHY0aLr9 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content4"));
                    return Content4__zHY0aLr9;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content4(object reward1, object reward2, object reward3, object reward4)
                {
                    if (Content4__zHY0aLr9 == null)
                        Content4__zHY0aLr9 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content4"));
                    return string.Format(Content4__zHY0aLr9.FormatString, reward1, reward2, reward3, reward4);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Content4(global::System.IFormatProvider provider, object reward1, object reward2, object reward3, object reward4)
                {
                    if (Content4__zHY0aLr9 == null)
                        Content4__zHY0aLr9 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$Content4"));
                    return string.Format(provider, Content4__zHY0aLr9.FormatString, reward1, reward2, reward3, reward4);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString RewardCredits__pWV0nt48;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardCredits")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardCredits()
                {
                    if (RewardCredits__pWV0nt48 == null)
                        RewardCredits__pWV0nt48 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardCredits"));
                    return RewardCredits__pWV0nt48;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardCredits(object value)
                {
                    if (RewardCredits__pWV0nt48 == null)
                        RewardCredits__pWV0nt48 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardCredits"));
                    return string.Format(RewardCredits__pWV0nt48.FormatString, value);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardCredits(global::System.IFormatProvider provider, object value)
                {
                    if (RewardCredits__pWV0nt48 == null)
                        RewardCredits__pWV0nt48 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardCredits"));
                    return string.Format(provider, RewardCredits__pWV0nt48.FormatString, value);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString RewardExp__K08FVRJo;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardExp")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardExp()
                {
                    if (RewardExp__K08FVRJo == null)
                        RewardExp__K08FVRJo = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardExp"));
                    return RewardExp__K08FVRJo;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardExp(object value)
                {
                    if (RewardExp__K08FVRJo == null)
                        RewardExp__K08FVRJo = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardExp"));
                    return string.Format(RewardExp__K08FVRJo.FormatString, value);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardExp(global::System.IFormatProvider provider, object value)
                {
                    if (RewardExp__K08FVRJo == null)
                        RewardExp__K08FVRJo = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardExp"));
                    return string.Format(provider, RewardExp__K08FVRJo.FormatString, value);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString RewardGp__CKVytu1D;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardGp")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardGp()
                {
                    if (RewardGp__CKVytu1D == null)
                        RewardGp__CKVytu1D = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardGp"));
                    return RewardGp__CKVytu1D;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardGp(object value)
                {
                    if (RewardGp__CKVytu1D == null)
                        RewardGp__CKVytu1D = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardGp"));
                    return string.Format(RewardGp__CKVytu1D.FormatString, value);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardGp(global::System.IFormatProvider provider, object value)
                {
                    if (RewardGp__CKVytu1D == null)
                        RewardGp__CKVytu1D = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardGp"));
                    return string.Format(provider, RewardGp__CKVytu1D.FormatString, value);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString RewardHath__ATfix75_;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardHath")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardHath()
                {
                    if (RewardHath__ATfix75_ == null)
                        RewardHath__ATfix75_ = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardHath"));
                    return RewardHath__ATfix75_;
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardHath(object value)
                {
                    if (RewardHath__ATfix75_ == null)
                        RewardHath__ATfix75_ = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardHath"));
                    return string.Format(RewardHath__ATfix75_.FormatString, value);
                }
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.RewardHath(global::System.IFormatProvider provider, object value)
                {
                    if (RewardHath__ATfix75_ == null)
                        RewardHath__ATfix75_ = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/$RewardHath"));
                    return string.Format(provider, RewardHath__ATfix75_.FormatString, value);
                }
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/Title")]
                string global::ExDawnOfDayTask.ResourceInfo.Resources.IDawnOfDayToast.Title
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///ExDawnOfDayTask/Resources/DawnOfDayToast/Title");
            }

        }
    }
}
